#version: '3.8'
#
#services:
#  mongodb:
#    image: mongo:latest
#    container_name: moviebooking-mongodb
#    ports:
#      - "27017:27017"
#    environment:
#      MONGO_INITDB_DATABASE: moviebooking_db
#    volumes:
#      - mongo_data:/data/db
#    networks:
#      - moviebooking-network
#
#  mongo-express:
#    image: mongo-express:latest
#    container_name: moviebooking-mongo-express
#    ports:
#      - "8081:8081"
#    environment:
#      ME_CONFIG_MONGODB_SERVER: mongodb
#      ME_CONFIG_MONGODB_PORT: 27017
#      ME_CONFIG_BASICAUTH: "false"
#    depends_on:
#      - mongodb
#    networks:
#      - moviebooking-network
#
#volumes:
#  mongo_data:
#
#networks:
#  moviebooking-network:
#
#
#
##version: '3'
##services:
##  zookeeper:
##    image: confluentinc/cp-zookeeper:7.3.0
##    ports:
##      - "2181:2181"
##    environment:
##      ZOOKEEPER_CLIENT_PORT: 2181
##
##  kafka:
##    image: confluentinc/cp-kafka:7.3.0
##    ports:
##      - "9092:9092"
##    environment:
##      KAFKA_BROKER_ID: 1
##      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
##      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
##    depends_on:
##      - zookeeper
