input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["spring-boot-logs"]
    group_id => "logstash-group"
    codec => "json"
  }
  tcp {
      port => 5000
      codec => json
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
    user => "elastic"
    password => "elastic123"
  }
  stdout { codec => rubydebug }
}
